<?php 
if(!class_exists('Site'))die(JText::_('RESTRICTED_ACCESS'));

if(gbl::getContextUser() == ''){
	ErrorHandler::fatalError("context user hasn't been set properly.");
}
include('client_proj_task_javascript.class.php');
$js = new ClientProjTaskJavascript();
?>
<script type="text/javascript" src="<?php echo Config::getRelativeRoot();?>/js/client_proj_task_javascript.js"></script>

<script type="text/javascript">
	//set initial values
	<?php
	echo "var initialClientId = ".gbl::getClientId().";\n";
	echo "var initialProjectId = ".gbl::getProjId().";\n";
	echo "var initialTaskId = ".gbl::getTaskId().";\n";
  ?>
	//define the hash table
	var projectTasksHash;
	var clientProjectsHash;
  <?php	
	$js->printJSONObjects();
  ?>  
	//parse the JSON Objects generated by the PHP script
	parseJSON();
  //console.log(jsonClientProjectsHash);
</script>