<?php ErrorHandler::fatalError('Error: This file ('.__FILE__.'has been deprecated.  Please stop using it<br />'.ppr(getShortDebugTrace(3),'trace',true));?>
<table width="100%" border="0" cellpadding="0" cellspacing="0">	   
  <tr>		     
    <td>			       
      <table width="100%" border="0" cellpadding="0" cellspacing="0">				         
        <tr>					           
          <td width="6" height="3">						             
            <img src="<?php echo Config::getRelativeRoot();?>/images/timesheet_face_01.gif" width="6" height="3" alt=""/></td>					           
          <td width="100%" height="3">						             
            <img src="<?php echo Config::getRelativeRoot();?>/images/timesheet_face_02.gif" width="100%" height="3" alt=""/></td>					           
          <td width="12" height="3">						             
            <img src="<?php echo Config::getRelativeRoot();?>/images/timesheet_face_03.gif" width="12" height="3" alt=""/></td>				         
        </tr>			       
      </table>		     
    </td>	   
  </tr>	   
  <tr>		     <td>			       
      <table width="100%" border="0" cellpadding="0" cellspacing="0">				         
        <tr>					           
          <td style="vertical-align:top;width:4px;background-image:url('<?php echo Config::getRelativeRoot();?>/images/timesheet_face_07.gif');background-repeat:y-repeat;">					             
            <div style="width:4px;background-repeat:no-repeat;background-image:url('<?php echo Config::getRelativeRoot();?>/images/timesheet_face_04.gif');">
            </div>
            <!--table width="4" height="100%" border="0" cellpadding="0" cellspacing="0">
							<tr>
								<td width="4" height="7">
									<img src="<? echo $tsx_registry->relativeRoot."/";?>images/timesheet_face_04.gif" width="4" height="7"  alt=\"\" /></td>
							</tr>
							<tr>
								<td style="width:4px;background-image:url('<? echo config::getRelativeRoot()."/";?>images/timesheet_face_07.gif');background-repeat:y-repeat;">&nbsp;</td>
							</tr>
						</table-->							     
          </td>					     
          <td style="width:100%; background-image: url('<?php echo Config::getRelativeRoot();?>/images/timesheet_face_05.gif');">					       
            <!-- BREAK POINT 1 -->