<?php ErrorHandler::fatalError('Error: This file ('.__FILE__.'has been deprecated.  Please stop using it<br />'.ppr(getShortDebugTrace(3),'trace',true));?>
								<!-- BREAK POINT 2 -->
									</td>
							</tr>
						</table>
					</td>
					<td style="vertical-align:top; width:10px; height:100%;">
						<table width="10" border="0" cellpadding="0" cellspacing="0">
							<tr>
								<td style="vertical-align:top; width:10px; height:19px;">
									<img src="<?php echo Config::getRelativeRoot();?>/images/timesheet_face_13.gif" width="10" height="19" alt="" /></td>
							</tr>
							<tr >
								<td width="10" height="100%">
									<img src="<?php echo Config::getRelativeRoot();?>/images/timesheet_face_16.gif" width="10" height="100%" alt="" /></td>
							</tr>
							<tr>
								<td width="10" height="6">
									<img src="<?php echo Config::getRelativeRoot();?>/images/timesheet_face_18.gif" width="10" height="6" alt="" /></td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td width="100%">
			<table width="100%" border="0" cellpadding="0" cellspacing="0">
				<tr>
					<td width="14" height="11">
						<img src="<?php echo Config::getRelativeRoot();?>/images/timesheet_face_19.gif" width="14" height="11" alt="" /></td>
					<td width="100%" height="11">
						<table width="100%" border="0" cellpadding="0" cellspacing="0">
							<tr>
								<td colspan="3" width="100%" height="1" class="faceBackground">
									<img src="<?php echo Config::getRelativeRoot();?>/images/spacer.gif" width="100%" height="1" alt="" /></td>
							</tr>
							<tr>
								<td width="2" height="10">
									<img src="<?php echo Config::getRelativeRoot();?>/images/timesheet_face_22.gif" width="2" height="10" alt="" /></td>
								<td width="100%" height="10">
									<img src="<?php echo Config::getRelativeRoot();?>/images/timesheet_face_23.gif" width="100%" height="10" alt="" /></td>
								<td width="2" height="10">
									<img src="<?php echo Config::getRelativeRoot();?>/images/timesheet_face_24.gif" width="2" height="10" alt="" /></td>
							</tr>
						</table>
					</td>
					<td width="11" height="11">
						<img src="<?php echo Config::getRelativeRoot();?>/images/timesheet_face_21.gif" width="11" height="11" alt="" /></td>
				</tr>
			</table>
		</td>
	</tr>
</table>
