<?php 
if(class_exists('Site'))ErrorHandler::fatalError('Error: old file.  please use timesheet_face_part_1new.inc<br />'.ppr(getShortDebugTrace(3),'trace',true));
?>
<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td>
			<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
				<tr>
					<td width="6" height="3">
						<img src="images/timesheet_face_01.gif" width="6" height="3" alt=""/></td>
					<td width="100%" height="3">
						<img src="images/timesheet_face_02.gif" width="100%" height="3" alt=""/></td>
					<td width="12" height="3">
						<img src="images/timesheet_face_03.gif" width="12" height="3" alt=""/></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td>
			<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
				<tr>
					<td width="4" height="100%">
						<table width="4" height="100%" border="0" cellpadding="0" cellspacing="0">
							<tr>
								<td width="4" height="7">
									<img src="images/timesheet_face_04.gif" width="4" height="7" alt=""/></td>
							</tr>
							<tr>
								<td width="4" height="100%">
									<img src="images/timesheet_face_07.gif" width="4" height="100%" alt=""/></td>
							</tr>
						</table>
					</td>
					<td background="images/timesheet_face_05.gif">
					<!-- BREAK POINT 1 -->
